# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Basys3-Master.xdc

# Block Designs: bd/design_leds/design_leds.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_leds || ORIG_REF_NAME==design_leds} -quiet] -quiet

# IP: bd/design_leds/ip/design_leds_leds_0_0/design_leds_leds_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_leds_leds_0_0 || ORIG_REF_NAME==design_leds_leds_0_0} -quiet] -quiet

# XDC: /home/yovick/repos/UAZ-IEI/5to Semestre/arquitecturaDeComputadoras/vivado/project_1/project_1.gen/sources_1/bd/design_leds/design_leds_ooc.xdc
